stages:
- build

ubuntu-self-contained:
  stage: build
  image: ubuntu:18.04
  script:
  - whoami
  - cat /etc/apt/sources.list
  - sed -i~orig -e 's/# deb-src/deb-src/' /etc/apt/sources.list
  - cat /etc/apt/sources.list
  - add-apt-repository main
  - add-apt-repository universe
  - add-apt-repository restricted
  - add-apt-repository multiverse
  - cat /etc/apt/sources.list
  - apt-get update
  - apt-get install -y -q \
    apt-utils build-essential cmake python-dev sudo git \
    devscripts equivs libcurl4-openssl-dev \
    ccache python3 python3-pip curl libssl-dev libzstd-dev \
    libevent-dev dpatch gawk gdb libboost-dev libcrack2-dev \
    libjudy-dev libnuma-dev libsnappy-dev libxml2-dev \
    unixodbc-dev uuid-dev fakeroot iputils-ping
  - mkdir build
  - mkdir build/mkdist
  - cd build/mkdist
  - cmake ../..

build win x86_64:
  stage: build
  tags:
    - win
    - x86_64
  script:
    - echo "I am a build stage job for win x86_64"
    
build osx:
  stage: build
  tags:
  - osx
  script:
  - echo "Hello, $USER"
    
build windows:
  stage: build
  tags:
  - windows
  script:
    - echo "Hello, %USERNAME%!"
