stages:
- build

ubuntu-self-contained:
  stage: build
  image: ubuntu:18.04
  script:
  - mkdir build
  - mkdir mkdist
  - cd build/mkdist
  - cmake ../..

ubuntu-system-dependencies:
  stage: build
  image: ubuntu:18.04
  script:
  - sed -i~orig -e 's/# deb-src/deb-src/' /etc/apt/sources.list
  - apt-get update
  - apt-get install -y -q \
    apt-utils build-essential python-dev sudo git \
    devscripts equivs libcurl4-openssl-dev \
    ccache python3 python3-pip curl libssl-dev libzstd-dev \
    libevent-dev dpatch gawk gdb libboost-dev libcrack2-dev \
    libjudy-dev libnuma-dev libsnappy-dev libxml2-dev \
    unixodbc-dev uuid-dev fakeroot iputils-ping