# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

resources:
    containers:

    - container: rhel-6
      image: mariadbe.azurecr.io/build-es:rhel-6
      endpoint: acr-mariadbe-connection
      options: --shm-size 12G

    - container: rhel-7
      image: mariadbe.azurecr.io/build-es:rhel-7
      endpoint: acr-mariadbe-connection
      options: --shm-size 12G

    - container: rhel-8
      image: mariadbe.azurecr.io/build-es:rhel-8
      endpoint: acr-mariadbe-connection
      options: --shm-size 12G

    - container: sles-12
      image: mariadbe.azurecr.io/build-es:sles-12
      endpoint: acr-mariadbe-connection
      options: --shm-size 12G

    - container: sles-15
      image: mariadbe.azurecr.io/build-es:sles-15
      endpoint: acr-mariadbe-connection
      options: --shm-size 12G

    - container: ubuntu-1604
      image: mariadbe.azurecr.io/build-es:ubuntu-1604
      endpoint: acr-mariadbe-connection
      options: --shm-size 12G

    - container: ubuntu-1804
      image: mariadbe.azurecr.io/build-es:ubuntu-1804
      endpoint: acr-mariadbe-connection
      options: --shm-size 12G

    - container: debian-8
      image: mariadbe.azurecr.io/build-es:debian-8
      endpoint: acr-mariadbe-connection
      options: --shm-size 12G

    - container: debian-9
      image: mariadbe.azurecr.io/build-es:debian-9
      endpoint: acr-mariadbe-connection
      options: --shm-size 12G

    - container: debian-10
      image: mariadbe.azurecr.io/build-es:debian-10
      endpoint: acr-mariadbe-connection
      options: --shm-size 12G

variables:
  BUILDDIR: "$(Build.SourcesDirectory)/padding_for_CPACK_RPM_BUILD_SOURCE_DIRS_PREFIX_ON_ES_BACKUP_DEBUGSOURCE"
  DEB_LOCAL_LIST: '/etc/apt/sources.list.d/localInstall.list'
  MYSQL_PASSWORD: 'tESt123%_password'
  ESTOKEN: '49bc85f8-6e90-443d-901a-b7f01a4ab22c'
  CS_REPO_URL: 'https://downloads.mariadb.com/MariaDB/mariadb_repo_setup'
  ES_REPO_URL: 'https://dlm.mariadb.com/enterprise-release-helpers/mariadb_es_repo_setup'

stages:

- stage: BuildPackages
  jobs:
  - template: azure/stage0/build-source-tarball.yml
  - template: azure/stage0/build-rpm-packages.yml
  - template: azure/stage0/build-deb-packages.yml

- stage: Upgrade_CS_10_2_to_ES_10_4
  jobs:
  - template: azure/stage3-upgrade.yml
    parameters:
      VERSION: '10.2'
      FROM: 'CS'
      FROMVERSION: '10_2'
      TO: 'ES'
      TOVERSION: '10_4'
      REPO: $(CS_REPO_URL)
      REPO_PARAMS: '--mariadb-server-version=mariadb-10.2'

- stage: Upgrade_CS_10_3_to_ES_10_4
  condition: succeededOrFailed()
  jobs:
  - template: azure/stage3-upgrade.yml
    parameters:
      VERSION: '10.3'
      FROM: 'CS'
      FROMVERSION: '10_3'
      TO: 'ES'
      TOVERSION: '10_4'
      REPO: $(CS_REPO_URL)
      REPO_PARAMS: '--mariadb-server-version=mariadb-10.3'

- stage: Upgrade_CS_10_4_to_ES_10_4
  condition: succeededOrFailed()
  jobs:
  - template: azure/stage3-upgrade.yml
    parameters:
      VERSION: '10.4'
      FROM: 'CS'
      FROMVERSION: '10_4'
      TO: 'ES'
      TOVERSION: '10_4'
      REPO: $(CS_REPO_URL)
      REPO_PARAMS: '--mariadb-server-version=mariadb-10.4'


- stage: Upgrade_ES_10_2_to_ES_10_4
  condition: succeededOrFailed()
  jobs:
  - template: azure/stage3-upgrade.yml
    parameters:
      VERSION: '10.2'
      FROM: 'ES'
      FROMVERSION: '10_2'
      TO: 'ES'
      TOVERSION: '10_4'
      REPO: $(ES_REPO_URL)
      REPO_PARAMS: '--token=$(ESTOKEN) --apply --verbose --mariadb-server-version=10.2'

- stage: Upgrade_ES_10_3_to_ES_10_4
  condition: succeededOrFailed()
  jobs:
  - template: azure/stage3-upgrade.yml
    parameters:
      VERSION: '10.3'
      FROM: 'ES'
      FROMVERSION: '10_3'
      TO: 'ES'
      TOVERSION: '10_4'
      REPO: $(ES_REPO_URL)
      REPO_PARAMS: '--token=$(ESTOKEN) --apply --verbose --mariadb-server-version=10.3'

- stage: Upgrade_ES_10_4_to_ES_10_4
  condition: succeededOrFailed()
  jobs:
  - template: azure/stage3-upgrade.yml
    parameters:
      VERSION: '10.4'
      FROM: 'ES'
      FROMVERSION: '10_4'
      TO: 'ES'
      TOVERSION: '10_4'
      REPO: $(ES_REPO_URL)
      REPO_PARAMS: '--token=$(ESTOKEN) --apply --verbose --mariadb-server-version=10.4'

- stage: RollingUpgrade_ES_10_2_to_ES_10_4
  condition: succeededOrFailed()
  jobs:
  - template: azure/stage3-rolling-upgrade.yml
    parameters:
      VERSIONS: [ '10.2', '10.3', '10.4' ]






