parameters:
  BuildType: ''
  CMakeArgs: ''
  Artifact:  ''

jobs:

- job: BuildMacPackages_${{ parameters.Artifact }}
  dependsOn: BuildSourceTarball
  workspace:
    clean: all
  pool:
    vmImage: 'macOS-latest'

  steps:

  - template: extract-source-tarball.yml

  - script: |
      brew install jemalloc mhash curl gnutls openssl
    displayName: "brew install dependencies"

  - script: |
      cmake . -DCMAKE_BUILD_TYPE=${{ parameters.BuildType }} \
        -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl/ \
        -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib \
        -DBUILD_CONFIG=enterprise
    displayName: 'cmake configure MacOS'
    failOnStderr: false

  #- script: sed -i '' s/SIZEOF_CHARP/"sizeof(char *)"/g libmariadb/libmariadb/ma_dtoa.c
  #  displayName: "sed SIZEOF_CHARP"

  - script: make -j5 package
    displayName: 'make'
    failOnStderr: false

  - task: CopyFiles@2
    timeoutInMinutes: 2
    inputs:
      targetFolder: '$(Build.ArtifactStagingDirectory)'
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: '?(*.tar.gz|*.pkg)'

#   #- script: cd support-files/macOSpkg && ./mkpkg ../../mariadb*tar.gz && mv -vi *.pkg ../../

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'MacOS-Release'
